### ISSUE TITLE
Add option to write new config file

### ISSUE THREAD

**Issue by mcladyz** [yeoman/bower-requirejs#100]
Add option to write a new config file BASED on an existing file. Like so:

Usage: bower-requirejs [options]

General options:
  -h, --help              # Print options and usage
  -v, --version           # Print the version number
  -c, --config            # Path to your RequireJS config file
  -n, --new-config    # Write config to a new file, using existing config as a base (Implies --config)
...

OR

Usage: bower-requirejs [options]

General options:
  -h, --help              # Print options and usage
  -v, --version           # Print the version number
  -c, --config            # Path to your RequireJS config file
  -s, --stdout            # Write config to stdout only
...

This way you can always update the original file in-place and just run bower-requirejs on the same file repeatedly, when testing your configuration.

**Comment by arthurvr** [comment]
I agree with @bezoerb. Don't really think it's needed.
