### ISSUE TITLE
inherit `baseUrl` from config.js if present

### ISSUE THREAD

**Issue by zanona** [yeoman/bower-requirejs#104]
Hey guys,
it would be nice if bower-requirers could inherit the parameter `baseUrl` from `config.js` if that was existent.

This would make it possible to only add this declaration once instead twice (one in config.js and another on the script command)

**Comment by arthurvr** [comment]
This got fixed together with this PR: https://github.com/yeoman/bower-requirejs/pull/78. Thanks for taking the time to open the issue!
