### ISSUE TITLE
cdnify support

### ISSUE THREAD

**Issue by kryptt** [yeoman/bower-requirejs#106]
It would be great if this plugin would use

https://github.com/passy/google-cdn#api

and / or info from a cdn package like:

https://github.com/shahata/jsdelivr-cdn-data

to optionally generate CDNiftied require lines!

**Comment by arthurvr** [comment]
Is this something we want in this module? I feel like it's a separated topic and worth something like a `requirejs-cdnify`.

**Comment by arthurvr** [comment]
@yeoman/bower-requirejs Thoughts? I personally feel like this is out of scope for this project.

**Comment by bezoerb** [comment]
+1 for separate repository.
