### ISSUE TITLE
prefix option to prefix module ids

### ISSUE THREAD

**Issue by arthurvr** [yeoman/bower-requirejs#108]
Ported over from https://github.com/yeoman/grunt-bower-requirejs/issues/31:

> Hey guys, what do you think about an option for prefixing all loaded module ids?
e.g. loglevel: 'js/loglevel/dist/loglevel.min' becomes base-loglevel: 'js/loglevel/dist/loglevel.min'

This issue should have been opened here, not in the grunt task.

**Comment by arthurvr** [comment]
@yeoman/bower-requirejs What do we think? Is this something we want?

**Comment by bezoerb** [comment]
i could not get the benefits from this. 
What about simply install with:
`bower install --save-dev base-loglevel=loglevel`

The resulting config would automatically look like this:
`'base-loglevel': 'base-loglevel/dist/loglevel.min',`

**Comment by arthurvr** [comment]
Agreed.
