### ISSUE TITLE
Allow running inside Docker containers

### ISSUE THREAD

**Issue by twogood** [yeoman/bower-requirejs#110]
When bower-requirejs is used inside a Docker container, it should probably allow running as root. Everything inside the container runs as the container root user, which is not the same as the actual root user on the Docker host.

Checking if running on Docker is as simple as checking for a file called /.dockerinit on the file system.

I also filed a similar issue with is-root (https://github.com/sindresorhus/sudo-block/issues/6), as I am unsure of what is the best place to fix this.

**Comment by arthurvr** [comment]
Closing as this is a feature request for sudo-block.
