### ISSUE TITLE
[Feature Request] CoffeeScript support?

### ISSUE THREAD

**Issue by alexandrosm** [yeoman/bower-requirejs#58]
I have my requirejs configuration file written in coffeescript, which unfortunately makes grunt-bower-requirejs not work. Any chance this use case can be supported? 

I am open to doing a PR if this is within scope of what you want for this plugin.

**Comment by andrewboni** [comment]
Would also love to have this. Anyone have any updates on making this play nicely with coffeescript? The workflow mentioned above sounds like it'd work, but it's not ideal
