### ISSUE TITLE
Problems with postinstall

### ISSUE THREAD

**Issue by axgen** [yeoman/bower-requirejs#82]
Hey,
I get an error while executing the postinstall task:

``` ruby
bower postinstall   bower-requirejs -c app/js/main.js
bower ENOENT        spawn ENOENT

Stack trace:
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

[...]
System info:

Bower version: 1.3.3
Node version: 0.10.26
OS: Windows_NT 6.1.7601 x64

I'm using requirejs v 1.3.3

Any ideas?

**Comment by whyleee** [comment]
I have the same error in Windows 8.1, and `./node_modules/.bin/bower-requirejs` path doesn't work. But `./node_modules/.bin/bower-requirejs.cmd` *does* work. This is weird, because this line is not cross-platform. Looks like this is Bower issue, right?

**Comment by whyleee** [comment]
Ok, I found a couple of ways to fix this problem:

1) Use `node path/to/bin.js ...` syntax instead:
In `.bowerrc`:
```
{
  "scripts": {
    "postinstall": "node ./node_modules/bower-requirejs/bin/bower-requirejs.js -c Scripts/config.js"
  }
}
```

2) Use npm to run the script:
In `.bowerrc`:
```
{
  "scripts": {
    "postinstall": "npm run bower-requirejs"
  }
}
```
In `package.json`:
```
{
  "scripts": {
    "bower-requirejs": "bower-requirejs -c Scripts/config.js"
  }
}
```
Second solution also allows to run the script manually: `npm run bower-requirejs`.
