### ISSUE TITLE
New maintainer needed

### ISSUE THREAD

**Issue by robdodson** [yeoman/bower-requirejs#86]
Since I'm not really using RequireJS anymore these days I haven't been able to devote much attention to this project. I would really love to find a new maintainer to take over responsibility for bower-requirejs and [grunt-bower-requirejs](https://github.com/yeoman/grunt-bower-requirejs). I'm more than happy to stay on and review issues and discuss things, I just won't have time to write new code.

Anyone up for the challenge?

**Comment by arthurvr** [comment]
Will see if I can work on some tickets.

**Comment by arthurvr** [comment]
We got down 10 tickets in here and the grunt task past day. Yay!

**Comment by bezoerb** [comment]
@arthurvr you rock! awesome :)

**Comment by kevva** [comment]
Great work :).
