### ISSUE TITLE
Node packages are added to the array every run

### ISSUE THREAD

**Issue by SneakyMax** [yeoman/bower-requirejs#87]
When a package is recognized as a node-style package (`dep.pgkMeta.moduleType == 'node'`), it will be added to the require.js packages list. However, when running bower-requirejs is run again, the packages list is appended to, rather than the existing package being modified.

E.g:
```
packages: [
        {
            name: "knockoutjs",
            main: "dist/knockout.js",
            location: "etc\\bower_components\\knockoutjs"
        },
        {
            name: "knockoutjs",
            main: "dist/knockout.js",
            location: "etc\\bower_components\\knockoutjs"
        }
    ]
```

**Comment by arthurvr** [comment]
> I think this issue was fixed in #96 ?

Yup! It was.
