### ISSUE TITLE
Add support for main in bower.json given as array of Strings

### ISSUE THREAD

**Issue by bartekbp** [yeoman/bower-requirejs#98]
Bower permits overriding dependency main:

``` javascript
{
  "name": "test",
  "version": "1.0.0",
  "dependencies": {
    "typeahead.js": "0.10.2"
  },
  "overrides": {
    "typeahead.js" : {
      "main": ["dist/bloodhound.js", "dist/typeahead.bundle.js"]
    }
  }
}
```

But such a config breaks plugin - main is assumed to be a String. Could you add support for this use case?

**Comment by xmlking** [comment]
in my case I have to override both `js` and `css` as the provider's bower.js contains `ng-table.min.js` and `ng-table.min.css`  , and I need  non-minified files as my workflow has its own minification step. 

```json
  "dependencies": {
    "ng-table": "~0.4.3",
  },
  "overrides": {
    "ng-table": {
      "main": [
        "dist/ng-table.js",
        "dist/ng-table.css"
      ]
    },
  }
```
It would  be nice if supported this feature.
