### ISSUE TITLE
Requirejs is not added to dependencies automatically

### ISSUE THREAD

**Issue by mcladyz** [yeoman/bower-requirejs#99]
readme.md states :

`Although RequireJS does not provide a bower.json file, a path to require.js will still be created in your rjsConfig file. The path's name will be requirejs. `

But this is not true if you run bower-requirejs CLI (Requirejs path is not added to config file). I think this is implemented only in bower-requirejs Grunt-task (See [pull request 35](https://github.com/yeoman/bower-requirejs/pull/35))?

**Comment by arthurvr** [comment]
> In my opinion this whole paragraph could be removed from the readme

I am +1. If nobody objects I can submit a PR.

**Comment by kevva** [comment]
+1.

**Comment by bezoerb** [comment]
+1
